// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airService.proto

package smart.building.airService;

public interface AirPuriRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart.AirPuriRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val = 1;</code>
   */
  java.lang.String getVal();
  /**
   * <code>string val = 1;</code>
   */
  com.google.protobuf.ByteString
      getValBytes();

  /**
   * <code>int32 figure = 2;</code>
   */
  int getFigure();
}
