// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airService.proto

package smart.building.airService;

public interface CurrentAirReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart.CurrentAirReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
