// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airService.proto

package smart.building.airService;

public interface CurrentAirRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart.CurrentAirRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string item = 1;</code>
   */
  java.lang.String getItem();
  /**
   * <code>string item = 1;</code>
   */
  com.google.protobuf.ByteString
      getItemBytes();
}
