// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envControl.proto

package smart.building.envControl;

public final class BuildingEnvControlServiceImpl {
  private BuildingEnvControlServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_HumidityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_HumidityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_HumidityReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_HumidityReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_ChangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_ChangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_ChangeReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_ChangeReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020envControl.proto\022\005smart\"1\n\017HumidityReq" +
      "uest\022\016\n\006status\030\001 \001(\t\022\016\n\006figure\030\002 \001(\005\" \n\r" +
      "HumidityReply\022\017\n\007message\030\001 \001(\t\"\037\n\rChange" +
      "Request\022\016\n\006status\030\001 \001(\t\"\036\n\013ChangeReply\022\017" +
      "\n\007message\030\001 \001(\t2\240\001\n\031BuildingEnvControlSe" +
      "rvice\022B\n\024airConditionerChange\022\024.smart.Ch" +
      "angeRequest\032\022.smart.ChangeReply\"\000\022?\n\rhum" +
      "idityCheck\022\026.smart.HumidityRequest\032\024.sma" +
      "rt.HumidityReply\"\000B<\n\031smart.building.env" +
      "ControlB\035BuildingEnvControlServiceImplP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smart_HumidityRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smart_HumidityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_HumidityRequest_descriptor,
        new java.lang.String[] { "Status", "Figure", });
    internal_static_smart_HumidityReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smart_HumidityReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_HumidityReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_smart_ChangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smart_ChangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_ChangeRequest_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_smart_ChangeReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smart_ChangeReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_ChangeReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
