// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envControl.proto

package smart.building.envControl;

public interface ChangeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart.ChangeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
