// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envControl.proto

package smart.building.envControl;

public interface ChangeReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart.ChangeReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
