// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envControl.proto

package smart.building.envControl;

public interface HumidityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart.HumidityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 figure = 2;</code>
   */
  int getFigure();
}
