// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthCheckService.proto

package smart.building.healthCheckService;

public interface AirAlarmReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart.AirAlarmReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
