// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthCheckService.proto

package smart.building.healthCheckService;

public interface BuildingAirRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart.BuildingAirRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string item = 1;</code>
   */
  java.lang.String getItem();
  /**
   * <code>string item = 1;</code>
   */
  com.google.protobuf.ByteString
      getItemBytes();
}
