// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthCheckService.proto

package smart.building.healthCheckService;

public final class HealthCheckServiceImpl {
  private HealthCheckServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_AirAlarmRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_AirAlarmRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_AirAlarmReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_AirAlarmReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_BuildingAirRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_BuildingAirRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_BuildingAirReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_BuildingAirReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030healthCheckService.proto\022\005smart\"\037\n\017Air" +
      "AlarmRequest\022\014\n\004item\030\001 \001(\t\" \n\rAirAlarmRe" +
      "ply\022\017\n\007message\030\001 \001(\t\"\"\n\022BuildingAirReque" +
      "st\022\014\n\004item\030\001 \001(\t\"#\n\020BuildingAirReply\022\017\n\007" +
      "message\030\001 \001(\t2\256\001\n\022HealthCheckService\022S\n\031" +
      "buildingAirConditionCheck\022\031.smart.Buildi" +
      "ngAirRequest\032\027.smart.BuildingAirReply\"\0000" +
      "\001\022C\n\017harmfulAirAlarm\022\026.smart.AirAlarmReq" +
      "uest\032\024.smart.AirAlarmReply\"\0000\001B=\n!smart." +
      "building.healthCheckServiceB\026HealthCheck" +
      "ServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smart_AirAlarmRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smart_AirAlarmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_AirAlarmRequest_descriptor,
        new java.lang.String[] { "Item", });
    internal_static_smart_AirAlarmReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smart_AirAlarmReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_AirAlarmReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_smart_BuildingAirRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smart_BuildingAirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_BuildingAirRequest_descriptor,
        new java.lang.String[] { "Item", });
    internal_static_smart_BuildingAirReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smart_BuildingAirReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_BuildingAirReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
